seed_everything: true

trainer:
  strategy: auto
  num_nodes: 1
  accelerator: cpu
  devices: 1
  precision: 32
  num_sanity_val_steps: 0
  use_distributed_sampler: false
  # optional for faster debugging:
  detect_anomaly: false
  log_every_n_steps: 1

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: Val/loss
        verbose: true
        save_top_k: 1
        mode: min

    - class_path: pytorch_lightning.callbacks.EarlyStopping
      init_args:
        monitor: Val/loss
        patience: 25
        mode: min

  fast_dev_run: false
  max_epochs: 500
  check_val_every_n_epoch: 250

  num_sanity_val_steps: 0      # âœ… avoids MPS warmup crash
  enable_progress_bar: true
  enable_model_summary: true
  enable_checkpointing: true
  detect_anomaly: true
  use_distributed_sampler: false

model:
  num_tokens: 6
  dim_model: 8
  dim_feedforward: 128
  num_heads: 4
  test_prompt_length: 6
  max_pred_length: 64
  num_decoder_layers: 2
  dropout_p: 0.1
  lr: 0.01
  layer_norm_eps: 2e-4
  model: transformer

data:
  num_train: 512
  num_val: 512
  num_test: 512
  max_length: 512
  batch_size: 128
  grammar: aNbNcN

notes: null
tags: null
ckpt_path: null
